spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project01
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create # DDL?? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
#    check-template-location: true
#        prefix: classpath:/templates/
#        suffix: .html
#    enabled: true
#  # 테스트시 에러나서 일단 임시로 막아둠

#  thymeleaf:
#    check-template-location: true
#
#  thymeleaf:
#    check-template-location: true

  #logging:
  #  level:
  #    org.hibernate.SQL: debug



  # application-oauth2.yml
  profiles:
    include: oauth2