spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 680325206505-vued3gde1osqa2qepaal5usv6pte65fu.apps.googleusercontent.com
            clientSecret: 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
            scope: email, profile


          naver:
            client-id: VqtA6qgpwLkRhVDjjTag
            client-secret: UDBJvNybx1
            redirect-uri: "http://localhost:8095/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: email, nickname

          kakao:
            client-id: 1463a3f1ba1564484ef82e8d8403c4cf
            client-secret: 5t1V7cl1yJkO2xRYCTAT2eOm5Q9toHZb
            redirect-uri: "http://localhost:8095/login/oauth2/code/kakao"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email #동의 항목
            client-name: Kakao    # 대문자 주의


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response	# naver 가 보내주는 사용자 정보 response = { email:, name: }

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id